apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "pod-policy.example.com"
webhooks:
- name: "pod-policy.example.com"
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["pods"]
    scope:       "Namespaced"
  clientConfig:
    service:
      namespace: "mutatingwebhook"
      name: "mutatingwebhook"
    caBundle: "Ci0tLS0tQk...<`caBundle` is a PEM encoded CA bundle which will be used to validate the webhook's server certificate.>...tLS0K"
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  timeoutSeconds: 5
---
apiVersion: v1
kind: Namespace
metadata:
  name: mutatingwebhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutatingwebhook
  labels:
    app: mutatingwebhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutatingwebhook
  template:
    metadata:
      labels:
        app: mutatingwebhook
    spec:
      containers:
      - name: mutatingwebhook
        image: wardviaene/mutatingwebhook-example
        ports:
        - containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: mutatingwebhook
spec:
  selector:
    app: mutatingwebhook
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443